# Generated by Django 4.2.7 on 2025-07-09 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('description', models.TextField(verbose_name='상품 설명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='원가')),
                ('discount_rate', models.IntegerField(default=0, verbose_name='할인율 (%)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='상품 이미지')),
                ('stock', models.IntegerField(default=0, verbose_name='재고')),
                ('status', models.CharField(choices=[('active', '활성'), ('inactive', '비활성'), ('sold_out', '품절')], default='active', max_length=20, verbose_name='상태')),
                ('is_featured', models.BooleanField(default=False, verbose_name='추천 상품')),
                ('is_new', models.BooleanField(default=False, verbose_name='신상품')),
                ('is_best_seller', models.BooleanField(default=False, verbose_name='베스트셀러')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(verbose_name='종료 시간')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='세일 가격')),
                ('max_quantity', models.IntegerField(default=0, verbose_name='최대 판매 수량')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='판매된 수량')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '타임세일',
                'verbose_name_plural': '타임세일들',
                'ordering': ['-created_at'],
            },
        ),
    ]
