# Generated by Django 4.2.7 on 2025-07-10 02:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='주문번호')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('shipped', '배송중'), ('delivered', '배송완료'), ('cancelled', '취소됨'), ('refunded', '환불됨')], default='pending', max_length=20, verbose_name='주문상태')),
                ('payment_status', models.CharField(choices=[('pending', '결제대기'), ('paid', '결제완료'), ('failed', '결제실패'), ('refunded', '환불완료')], default='pending', max_length=20, verbose_name='결제상태')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 금액')),
                ('shipping_address', models.TextField(verbose_name='배송주소')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='배송연락처')),
                ('shipping_name', models.CharField(max_length=100, verbose_name='수령인')),
                ('notes', models.TextField(blank=True, verbose_name='주문메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='주문자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_best_seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='timesale',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='timesale',
            name='sold_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='할인가격'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', '활성'), ('inactive', '비활성'), ('out_of_stock', '품절')], default='active', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='재고'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timesale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timesale',
            name='end_time',
            field=models.DateTimeField(verbose_name='종료시간'),
        ),
        migrations.AlterField(
            model_name='timesale',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_sale', to='products.product', verbose_name='상품'),
        ),
        migrations.AlterField(
            model_name='timesale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='할인가격'),
        ),
        migrations.AlterField(
            model_name='timesale',
            name='start_time',
            field=models.DateTimeField(verbose_name='시작시간'),
        ),
        migrations.AlterField(
            model_name='timesale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='단가')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 가격')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order', verbose_name='주문')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '주문상품',
                'verbose_name_plural': '주문상품들',
            },
        ),
    ]
